### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by ericgaspar**
## Problem

- *Description of why you made this PR*

## Solution

- *And how do you fix that problem*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Comment by OniriCorpe** [comment]
upgrade failed on my server .___.
and the log doesn't help .____.
https://paste.yunohost.org/raw/idicaciroz

**Comment by Josue-T** [comment]
> upgrade failed on my server 🙃 and the log doesn't help 🙃🙃 https://paste.yunohost.org/raw/idicaciroz

Look like an issue with your nginx config.You can check with nginx -t

**Comment by OniriCorpe** [comment]
> > upgrade failed on my server 🙃 and the log doesn't help 🙃🙃 [paste.yunohost.org/raw/idicaciroz](https://paste.yunohost.org/raw/idicaciroz)
> 
> Look like an issue with your nginx config.You can check with nginx -t

my config is fine and the update worked on my second try x)

so LGTM

**Pull request merged**
